#sudo: required
services:
  - docker

before_install:
  - docker build -t aquapevi/docker-react -f Dockerfile .

#script:
#  - docker run -e CI=true aquapevi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "ap-southeast-2"
  app: "docker-react-1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-344968910644"
  bucket_path: "docker-react-1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
